export const CREATE_PLAYER = "CREATE_PLAYER";
export const TOGGLE_ACTIVE_PLAYER = "TOGGLE_ACTIVE_PLAYER";
export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
export const TOGGLE_ACTIVE_CAMPAIGN = "TOGGLE_ACTIVE_CAMPAIGN";